"""empty message

Revision ID: adb74d2a2c56
Revises: 8fc887725d8a
Create Date: 2022-12-05 21:28:26.736477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adb74d2a2c56'
down_revision = '8fc887725d8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Brand', sa.String(length=100), nullable=True),
    sa.Column('Model', sa.String(length=100), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('FuelConsumption', sa.String(length=100), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('RentalCar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Price_for_1d', sa.Integer(), nullable=True),
    sa.Column('Days', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('Phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_index('id', table_name='car')
    op.drop_table('car')
    op.drop_index('id', table_name='order')
    op.drop_table('order')
    op.drop_index('id', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('surname', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'user', ['id'], unique=False)
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('car_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beginningDate', mysql.DATETIME(), nullable=True),
    sa.Column('amountOfDays', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('complete', mysql.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name='order_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='order_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'order', ['id'], unique=False)
    op.create_table('car',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'car', ['id'], unique=False)
    op.drop_table('User')
    op.drop_table('RentalCar')
    op.drop_table('Car')
    # ### end Alembic commands ###
